### ISSUE TITLE
Problem on running Train_NCBID.sh

### ISSUE THREAD

**Issue by kehan1** [DMnBI/mdi_predictor#2]
Hi, friend. When I running this file to produce the ncbi model, I encounter this  problem. Could you please take a look?

INFO 8917548-00 Pleiotropic defects in ataxia-telangiectasia protein-deficient mice. 
Exception in thread "main" java.lang.NullPointerException
        at ncbi.taggerOne.model.normalization.AveragedNormalizationModel.score(AveragedNormalizationModel.java:168)
        at ncbi.taggerOne.model.normalization.NormalizationModel.findBestName(NormalizationModel.java:235)
        at ncbi.taggerOne.model.normalization.CachedNormalizationModel.findBestName(CachedNormalizationModel.java:115)
        at ncbi.taggerOne.processing.analysis.ErrorAnalyzer.visualizeSegmentError(ErrorAnalyzer.java:177)
        at ncbi.taggerOne.processing.analysis.ErrorAnalyzer.process(ErrorAnalyzer.java:57)
        at ncbi.taggerOne.processing.textInstance.TextInstanceProcessingPipeline.process(TextInstanceProcessingPipeline.java:39)
        at ncbi.taggerOne.processing.stoppingCriteria.EvaluationProcessorStoppingCriteria.stop(EvaluationProcessorStoppingCriteria.java:85)
        at ncbi.taggerOne.processing.textInstance.AnnotationModelTrainer.processAll(AnnotationModelTrainer.java:72)
        at ncbi.taggerOne.TrainModel.main(TrainModel.java:482)

**Comment by yesol-park** [comment]
Thanks for your interest in our project.

Our code has been modified to use the pre-trained model from TaggerOne-0.2.1/output. Please update the git project and follow steps in Exec section.
